dist: focal
language: node_js
node_js: 
  - 16
  
before_install:

os:
  - linux
  - osx
  - windows


script:
  - npx scrypt-cli compile
  - npm run build
  - npm t -- --watchAll=false
